In [1]:
# EDA steps:
•	Import the Data-set
•	Read data
•	Check data characters
•	Calculating statistics: mean, median, standard deviation
•	Basic plotting for data
•	Correlation computation
•   Correlation Heat Map

# Data pre-processing steps:
•	Import the Libraries
•	Check out & filled the missing values
•   Group by function
•   Logistic Regrssion & Handle /Create Dummy variable
•   Decision Tree Classifier
•   Support Vector Machine
•   Random forest
•   AdaBoost
•	PCA

EDA Steps

In [3]:
# Import the Data-set & Import the Libraries

In [4]:
# numpy and pandas for data manipulation
import pandas as pd
import numpy as np
# matplotlib and seaborn for plotting
import matplotlib
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import Imputer 
from sklearn.preprocessing import scale 

In [5]:
# Read Data

In [6]:
app_train = pd.read_csv("/dbfs/FileStore/tables/application_train.csv", header='infer')
app_test = pd.read_csv("/dbfs/FileStore/tables/application_test.csv", header='infer')
bureau = pd.read_csv("/dbfs/FileStore/tables/bureau.csv", header='infer')
bureau_balance = pd.read_csv("/dbfs/FileStore/tables/bureau_balance.csv", header='infer')

In [7]:
# Check data characters & calculating statistics: mean, median, standard deviation

In [8]:
app_train['TARGET'].value_counts()

Out[ 5 ]: 
0 282686
1 24825
Name: TARGET, dtype: int64

In [9]:
print('AMT_INCOME_TOTAL Train',app_train['AMT_INCOME_TOTAL'].count())

AMT_INCOME_TOTAL Train 307511

In [10]:
# Basic plotting for data

In [11]:
app_train['TARGET'].astype(int).plot.hist()

Out[ 8 ]: <matplotlib.axes._subplots.AxesSubplot at 0x7f2ae9514a90>

In [12]:
# Correlation computation

In [13]:
# Find correlations with the target and sort
correlations = app_train.corr()['TARGET'].sort_values()

# Display correlations
print('Most Positive Correlations:\n', correlations.tail(20))
print('\nMost Negative Correlations:\n', correlations.head(20))

Most Positive Correlations:
 OBS_30_CNT_SOCIAL_CIRCLE 0.009131
CNT_FAM_MEMBERS 0.009308
CNT_CHILDREN 0.019187
AMT_REQ_CREDIT_BUREAU_YEAR 0.019930
FLAG_WORK_PHONE 0.028524
DEF_60_CNT_SOCIAL_CIRCLE 0.031276
DEF_30_CNT_SOCIAL_CIRCLE 0.032248
LIVE_CITY_NOT_WORK_CITY 0.032518
OWN_CAR_AGE 0.037612
DAYS_REGISTRATION 0.041975
FLAG_DOCUMENT_3 0.044346
REG_CITY_NOT_LIVE_CITY 0.044395
FLAG_EMP_PHONE 0.045982
REG_CITY_NOT_WORK_CITY 0.050994
DAYS_ID_PUBLISH 0.051457
DAYS_LAST_PHONE_CHANGE 0.055218
REGION_RATING_CLIENT 0.058899
REGION_RATING_CLIENT_W_CITY 0.060893
DAYS_BIRTH 0.078239
TARGET 1.000000
Name: TARGET, dtype: float64

Most Negative Correlations:
 EXT_SOURCE_3 -0.178919
EXT_SOURCE_2 -0.160472
EXT_SOURCE_1 -0.155317
DAYS_EMPLOYED -0.044932
FLOORSMAX_AVG -0.044003
FLOORSMAX_MEDI -0.043768
FLOORSMAX_MODE -0.043226
AMT_GOODS_PRICE -0.039645
REGION_POPULATION_RELATIVE -0.037227
ELEVATORS_AVG -0.034199
ELEVATORS_MEDI -0.033863
FLOORSMIN_AVG -0.033614
FLOORSMIN_MEDI -0.033394
LIVINGAREA_AVG -0.032997
LIVINGAREA_MEDI -0.032739
FLOORSMIN_MODE -0.032698
TOTALAREA_MODE -0.032596
ELEVATORS_MODE -0.032131
LIVINGAREA_MODE -0.030685
AMT_CREDIT -0.030369
Name: TARGET, dtype: float64

In [14]:
# Correlation Heat Map

In [15]:
ext_data = app_train[['TARGET', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'DAYS_BIRTH']]
ext_data_corrs = ext_data.corr()
ext_data_corrs

plt.figure(figsize = (8, 6))

# Heatmap of correlations
sns.heatmap(ext_data_corrs, cmap = plt.cm.RdYlBu_r, vmin = -0.25, annot = True, vmax = 0.6)
plt.title('Correlation Heatmap');

Data pre-processing steps

In [17]:
# Import the Libraries

In [18]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import time
# Decision Tree Classifier
from sklearn import datasets
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
# Support Vector Machine
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
# Random forest
from sklearn.ensemble import RandomForestClassifier
# AdaBoost
from sklearn.ensemble import AdaBoostClassifier #For Classification
from sklearn.ensemble import AdaBoostRegressor #For Regression
from sklearn.tree import DecisionTreeClassifier
app_train = pd.read_csv("/dbfs/FileStore/tables/application_train.csv", header='infer')
app_test = pd.read_csv("/dbfs/FileStore/tables/application_test.csv", header='infer')

In [19]:
# Suppress warnings from pandas
import warnings
warnings.filterwarnings('ignore')
plt.style.use('fivethirtyeight')

In [20]:
# Check out & filled the missing values

In [21]:
# Function to calculate missing values by column# Funct 
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [22]:
# Missing values statistics
missing_values = missing_values_table(app_train)
missing_values.head(20)

Your selected dataframe has 122 columns.
There are 67 columns that have missing values.
 Out[ 18 ]: 
 Missing Values % of Total Values
COMMONAREA_MEDI 214865 69.9
COMMONAREA_AVG 214865 69.9
COMMONAREA_MODE 214865 69.9
NONLIVINGAPARTMENTS_MEDI 213514 69.4
NONLIVINGAPARTMENTS_MODE 213514 69.4
NONLIVINGAPARTMENTS_AVG 213514 69.4
FONDKAPREMONT_MODE 210295 68.4
LIVINGAPARTMENTS_MODE 210199 68.4
LIVINGAPARTMENTS_MEDI 210199 68.4
LIVINGAPARTMENTS_AVG 210199 68.4
FLOORSMIN_MODE 208642 67.8
FLOORSMIN_MEDI 208642 67.8
FLOORSMIN_AVG 208642 67.8
YEARS_BUILD_MODE 204488 66.5
YEARS_BUILD_MEDI 204488 66.5
YEARS_BUILD_AVG 204488 66.5
OWN_CAR_AGE 202929 66.0
LANDAREA_AVG 182590 59.4
LANDAREA_MEDI 182590 59.4
LANDAREA_MODE 182590 59.4

In [23]:
# Group By Function

In [24]:
# Groupby the client id (SK_ID_CURR), count the number of previous loans, and rename the column
previous_loan_counts = bureau.groupby('SK_ID_CURR', as_index=False)['SK_ID_BUREAU'].count().rename(columns = {'SK_ID_BUREAU': 'previous_loan_counts'})
previous_loan_counts.head()

Out[ 20 ]: 
 SK_ID_CURR previous_loan_counts
0 100001 7
1 100002 8
2 100003 4
3 100004 2
4 100005 3

In [25]:
# app_train left join previous loan data
train = app_train.join(previous_loan_counts, on = 'SK_ID_CURR', how = 'left', lsuffix='SK_ID_CURR', rsuffix='r_SK_ID_CURR')

# Fill the missing values with 0 
train['previous_loan_counts'] = train['previous_loan_counts'].fillna(0)
train.head()

Out[ 21 ]: 
 SK_ID_CURRSK_ID_CURR TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR \
0 100002 1 Cash loans M N 
1 100003 0 Cash loans F N 
2 100004 0 Revolving loans M Y 
3 100006 0 Cash loans F N 
4 100007 0 Cash loans M N 

 FLAG_OWN_REALTY CNT_CHILDREN AMT_INCOME_TOTAL AMT_CREDIT AMT_ANNUITY \
0 Y 0 202500.0 406597.5 24700.5 
1 N 0 270000.0 1293502.5 35698.5 
2 Y 0 67500.0 135000.0 6750.0 
3 Y 0 135000.0 312682.5 29686.5 
4 Y 0 121500.0 513000.0 21865.5 

 ... FLAG_DOCUMENT_20 FLAG_DOCUMENT_21 \
0 ... 0 0 
1 ... 0 0 
2 ... 0 0 
3 ... 0 0 
4 ... 0 0 

 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY \
0 0.0 0.0 
1 0.0 0.0 
2 0.0 0.0 
3 NaN NaN 
4 0.0 0.0 

 AMT_REQ_CREDIT_BUREAU_WEEK AMT_REQ_CREDIT_BUREAU_MON \
0 0.0 0.0 
1 0.0 0.0 
2 0.0 0.0 
3 NaN NaN 
4 0.0 0.0 

 AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR \
0 0.0 1.0 
1 0.0 0.0 
2 0.0 0.0 
3 NaN NaN 
4 0.0 0.0 

 SK_ID_CURRr_SK_ID_CURR previous_loan_counts 
0 216379.0 1.0 
1 216380.0 8.0 
2 216381.0 4.0 
3 216383.0 2.0 
4 216384.0 2.0 

[5 rows x 124 columns]

In [26]:
## Model & Evaluation

# Next, I will use five different models, and evaluated on them by using F score.Turned out Logistic regrassion has the highest F1 score, 0.98. And the decison tree give the lowest F score, 0.89. Second highest F score model are SVM and Random forest (0.91). Adaboost and PCA gave the average F score of 0.90. 

# The reason for the different F score is because logistic regression model could handle the  continuous and categorical variables, which could increase the accuarcy of the model. For the decision tree, it has the tendency to overfit, they are prone to sampling errors. Also, tree splitting is locally greedy. Whcich may also descrease the accuaracy. In order to increase the accuaracy of the model, I used Randon forest.Random forest (and all other variations of the decision tree method) will only tell you which predictors are more important to build the trees, without any information on the direction of association. Thus, this model gave a higher F score. SVM model is an approximation to a bound on the test error rate, which can help increase the accuaracy, but choosing a “good” kernel function is not easy. So, it may lower the score. Meanwhile, Adaboost is a powerful classification algorithm, but it can be sensitive to noisy data and outliers, therfore, lower the F score. PCA is an efficient tool to reduce dimention, which may generate a higher F score

In [27]:
#Logistic Regression & Handle /Create Dummy variable

In [28]:
# one-hot encoding of categorical variables
app_train = pd.get_dummies(app_train)
app_test = pd.get_dummies(app_test)
print('Training Features shape: ', train.shape)

Training Features shape: (307511, 124)

In [29]:
# load the datasets
app_train = pd.read_csv("/dbfs/FileStore/tables/application_train.csv", header='infer')
app_train = pd.get_dummies(app_train)
app_train = app_train.dropna()

logreg = LogisticRegression()

X = app_train.drop(['TARGET'], axis=1)
y = app_train['TARGET']

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.4, random_state=42)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
from sklearn.metrics import roc_auc_score
log_reg = LogisticRegression()

## make predictions
X_test_predicted = model.predict(X_test)
# # summarize the fit of the model
print(metrics.classification_report(y_test, X_test_predicted))
print(metrics.confusion_matrix(y_test, X_test_predicted))

precision recall f1-score support

 0 0.98 1.00 0.99 4260
 1 1.00 0.72 0.83 281

avg / total 0.98 0.98 0.98 4541

[[4260 0]
 [ 80 201]]

In [30]:
# ROC_AUC score
from sklearn.metrics import roc_auc_score
logreg = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.4, random_state=42)
logreg.fit(X_train, y_train)
y_pred_prob = logreg.predict_proba(X_test)[:,1]
roc_auc_score(y_test, y_pred_prob)

Out[ 43 ]: 0.59802349088600404

In [31]:
# Decision Tree Classifier

In [32]:
# load the datasets
app_train = pd.read_csv("/dbfs/FileStore/tables/application_train.csv", header='infer')
app_train = pd.get_dummies(app_train)
app_train = app_train.dropna()

X = app_train.drop(['TARGET'], axis=1)
y = app_train['TARGET']
# Split dataset in training and test datasets
X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 0)

# fit a CART model to the data
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print(model)

# make predictions
X_test_predicted = model.predict(X_test)
# # summarize the fit of the model
print(metrics.classification_report(y_test, X_test_predicted))
print(metrics.confusion_matrix(y_test, X_test_predicted))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
 max_features=None, max_leaf_nodes=None,
 min_impurity_split=1e-07, min_samples_leaf=1,
 min_samples_split=2, min_weight_fraction_leaf=0.0,
 presort=False, random_state=None, splitter='best')
 precision recall f1-score support

 0 0.94 0.94 0.94 3199
 1 0.14 0.15 0.14 207

avg / total 0.90 0.89 0.89 3406

[[3001 198]
 [ 176 31]]

In [33]:
# Support Vector Machine

In [34]:
app_train = app_train.dropna()
# Split dataset in training and test datasets
X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 0)
# fit a SVM model to the data
model = SVC()
model.fit(X_train, y_train)
print(model)
# make predictions
X_test_predicted = model.predict(X_test)
# # summarize the fit of the model
print(metrics.classification_report(y_test, X_test_predicted))
print(metrics.confusion_matrix(y_test, X_test_predicted))

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
 decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
 max_iter=-1, probability=False, random_state=None, shrinking=True,
 tol=0.001, verbose=False)
 precision recall f1-score support

 0 0.94 1.00 0.97 3199
 1 0.00 0.00 0.00 207

avg / total 0.88 0.94 0.91 3406

[[3199 0]
 [ 207 0]]

In [35]:
# Random forest

In [36]:
# Make the random forest classifier
random_forest = RandomForestClassifier(n_estimators = 100, random_state = 50, verbose = 1, n_jobs = -1)
random_forest.fit(X_train, y_train)

# Make predictions on the test data
predictions = random_forest.predict_proba(X_test)[:, 1]

# # summarize the fit of the model
print(metrics.classification_report(y_test, X_test_predicted))
print(metrics.confusion_matrix(y_test, X_test_predicted))

[Parallel(n_jobs=-1)]: Done 34 tasks | elapsed: 0.5s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed: 1.2s finished
[Parallel(n_jobs=8)]: Done 34 tasks | elapsed: 0.1s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed: 0.1s finished
 precision recall f1-score support

 0 0.94 1.00 0.97 3199
 1 0.00 0.00 0.00 207

avg / total 0.88 0.94 0.91 3406

[[3199 0]
 [ 207 0]]

In [37]:
# AdaBoost

In [38]:
# Split dataset in training and test datasets
X_train, X_test,y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)
dt = DecisionTreeClassifier() 
clf = AdaBoostClassifier(n_estimators=100, base_estimator=dt,learning_rate=1)

# Above I have used decision tree as a base estimator, you can use any ML learner as base estimator if it ac# cepts sample weight 
clf.fit(X_train, y_train)

# Make predictions on the test data
predictions = random_forest.predict_proba(X_test)[:, 1]

# # summarize the fit of the model
print(metrics.classification_report(y_test, X_test_predicted))
print(metrics.confusion_matrix(y_test, X_test_predicted))

[Parallel(n_jobs=8)]: Done 34 tasks | elapsed: 0.1s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed: 0.2s finished
 precision recall f1-score support

 0 0.94 1.00 0.97 3187
 1 0.00 0.00 0.00 219

avg / total 0.88 0.94 0.90 3406

[[3187 0]
 [ 219 0]]

In [39]:
#PCA

In [40]:
#PCA
# matplotlit and seaborn for visualizations
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = 22
import seaborn as sns

# Suppress warnings from pandas
import warnings
warnings.filterwarnings('ignore')

from sklearn.decomposition import PCA
from sklearn.preprocessing import Imputer
from sklearn.pipeline import Pipeline

app_train = pd.read_csv("/dbfs/FileStore/tables/application_train.csv", header='infer')
app_test = pd.read_csv("/dbfs/FileStore/tables/application_test.csv", header='infer')

In [41]:
# Train missing values (in percent)
app_train_missing = (app_train.isnull().sum() / len(app_train)).sort_values(ascending = False)
app_train_missing.head()

Out[ 37 ]: 
COMMONAREA_MEDI 0.698723
COMMONAREA_AVG 0.698723
COMMONAREA_MODE 0.698723
NONLIVINGAPARTMENTS_MODE 0.694330
NONLIVINGAPARTMENTS_MEDI 0.694330
dtype: float64

In [42]:
# Test missing values (in percent)
app_test_missing = (app_test.isnull().sum() / len(app_test)).sort_values(ascending = False)
app_test_missing.head()

Out[ 38 ]: 
COMMONAREA_MEDI 0.687161
COMMONAREA_AVG 0.687161
COMMONAREA_MODE 0.687161
NONLIVINGAPARTMENTS_MODE 0.684125
NONLIVINGAPARTMENTS_MEDI 0.684125
dtype: float64

In [43]:
 # One hot encoding
app_train = pd.get_dummies(app_train)
app_test = pd.get_dummies(app_test)

# Match the columns in the dataframes
app_train, app_test = app_train.align(app_test, join = 'inner', axis = 1)
print('Training shape: ', app_train.shape)
print('Testing shape: ', app_test.shape)


Training shape: (307511, 242)
Testing shape: (48744, 242)

In [44]:
# Make a pipeline with imputation and pca
pipeline = Pipeline(steps = [('imputer', Imputer(strategy = 'median')),
             ('pca', PCA())])

# Fit and transform on the training data
app_train_pca = pipeline.fit_transform(app_train)

# transform the testing data
app_test_pca = pipeline.transform(app_test)

In [45]:
# Extract the pca object
pca = pipeline.named_steps['pca']

# Plot the cumulative variance explained

plt.figure(figsize = (10, 8))
plt.plot(list(range(app_train.shape[1])), np.cumsum(pca.explained_variance_ratio_), 'r-')
plt.xlabel('Number of PC'); plt.ylabel('Cumulative Variance Explained');
plt.title('Cumulative Variance Explained with PCA');

# # summarize the fit of the model
print(metrics.classification_report(y_test, X_test_predicted))
print(metrics.confusion_matrix(y_test, X_test_predicted))

precision recall f1-score support

 0 0.94 1.00 0.97 3187
 1 0.00 0.00 0.00 219

avg / total 0.88 0.94 0.90 3406

[[3187 0]
 [ 219 0]]